### ISSUE TITLE
Error importing bulma-tooltip

### ISSUE THREAD

**Issue by amir20** [Wikiki/bulma-tooltip#16]
Starting this morning I am seeing 

```
@import "~bulma-tooltip";
    ^
          File to import not found or unreadable: ~bulma-tooltip.
```

I think the problem is that in [package.json](https://github.com/Wikiki/bulma-tooltip/blob/master/package.json#L5) main points to `tooltip.sass` which isn't there. There is a dist folder.

**Comment by Wikiki** [comment]
Fixed.

**Comment by amir20** [comment]
Hmm, I don't think it's fixed yet. Now I get 

```
@import "initial-variables.sass"
^
      File to import not found or unreadable: initial-variables.sass.
Parent style sheet: /Users/amirraminfar/go/src/github.com/amir20/clashstats/node_modules/bulma-tooltip/dist/bulma-tooltip.sass
      in /Users/amirraminfar/go/src/github.com/amir20/clashstats/node_modules/bulma-tooltip/dist/bulma-tooltip.sass (line 3, column 1)
    at runLoaders (/Users/amirraminfar/go/src/github.com/amir20/clashstats/node_modules/webpack/lib/NormalModule.js:195:19)
    at /Users/amirraminfar/go/src/github.com/amir20/clashstats/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/amirraminfar/go/src/github.com/amir20/clashstats/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/amirraminfar/go/src/github.com/amir20/clashstats/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/Users/amirraminfar/go/src/github.com/amir20/clashstats/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/Users/amirraminfar/go/src/github.com/amir20/clashstats/node_modules/async/dist/async.js:2257:31)
    at Object.callback (/Users/amirraminfar/go/src/github.com/amir20/clashstats/node_modules/async/dist/async.js:958:16)
    at options.error (/Users/amirraminfar/go/src/github.com/amir20/clashstats/node_modules/node-sass/lib/index.js:294:32)

```

**Comment by Wikiki** [comment]
Are you using the last update ? Because there is no import initial-variables.sass within dist/bulma-tooltip.sass.

**Comment by amir20** [comment]
Hmm I am using version 1.0.0. `└── bulma-tooltip@1.0.0 `. I removed `node_modules` just to make sure and did `npm i` again. Inside the `bulma-tooltip` directory I see: 

```
head node_modules/bulma-tooltip/dist/bulma-tooltip.sass  
@charset "utf-8"

@import "initial-variables.sass"
@import "functions.sass"
@import "derived-variables.sass"
@import "animations.sass"
@import "mixins.sass"
@import "controls.sass"

$tooltip-background-color: $grey-dark !default
```

and `head node_modules/bulma-tooltip/package.json` shows `"_from": "bulma-tooltip@1.0.0",`

So I don't know what's going on. Perhaps a bad deploy?

**Comment by amir20** [comment]
I created a new project and did `npm i bulma-tooltip` and it has `initial-variables.scss` in it. 

https://asciinema.org/a/Zom2v7WURXAAwewFdQjIh2aa2

I honestly don't know where that's coming from.

**Comment by Wikiki** [comment]
I guess it's an issue with my npm publish because if I look at dist/tooltip.sass within the repository files are good.
I'll have a look at it.

**Comment by Wikiki** [comment]
Sorry I messed up with my publish task.
I've fixed it and republished the package.

**Comment by amir20** [comment]
Works now!

**Comment by Wikiki** [comment]
Glad to hear ;-)
